AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create VPC with Public Subnets,
  Internet Gateway, and Route Table,
  Replace YOUR-CIDR with your assigned octet, 
  Replace YOUR-ID with your Check Point AD name without "@checkpoint.com",
  

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.17.16.0/20
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Elastic-Beanstalk-mcastillo

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.17.16.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Description: VPC ID
  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Description: ID of the first public subnet
  PublicRouteTableId:
    Value: !Ref PublicRouteTable
    Description: ID of the public route table
  InternetGatewayId:
    Value: !Ref InternetGateway
    Description: ID of the internet gateway
